version: '3.2'
services:
  vending_machine_application:
    command: ./gradlew clean build -x test -x integrationTest
    build: .
    container_name: vending-machine-application
    expose:
        - 8080
    ports:
        - "8080:8080"
    depends_on:
        - vending_machine_db
  vending_machine_db:
    image: postgres:14.1
    container_name: postgres_db
    env_file:
        - database.env
    volumes:
        - .data-volume:/var/lib/postgresql/data/
    ports:
        - "5432:5432"
    deploy:
        resources:
            limits:
                cpus: "1"
                memory: 512M
            reservations:
                cpus: "1"
                memory: 512M
volumes:
  data-volume:

