spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console-enabled: false
    liquibase:
        change-log: classpath:liquibase/db-changelog-root.yaml